// <auto-generated />
using System;
using Employee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApiFuAgency.Migrations
{
    [DbContext(typeof(RolmexContext))]
    partial class RolmexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Employee.Entity.Dipartimenti", b =>
                {
                    b.Property<int>("GeoCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmagineDipartimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeaderEntrepriseId")
                        .HasColumnType("int");

                    b.Property<string>("Luogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeoCode");

                    b.HasIndex("LeaderEntrepriseId");

                    b.ToTable("Dipartimenti");
                });

            modelBuilder.Entity("Employee.Entity.Impiegato", b =>
                {
                    b.Property<int>("EntrepriseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dipartimento")
                        .HasColumnType("int");

                    b.Property<string>("ImmagineProfilo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RakingPoints")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntrepriseId");

                    b.ToTable("Impiegato");
                });

            modelBuilder.Entity("Employee.Entity.Dipartimenti", b =>
                {
                    b.HasOne("Employee.Entity.Impiegato", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderEntrepriseId");

                    b.Navigation("Leader");
                });
#pragma warning restore 612, 618
        }
    }
}
